package vista;

import control.Constantes;

/**
 *
 * @author moral
 */
public class TableroVista extends javax.swing.JFrame {

    private String tooltipNivelHab = "Se consigue en el nivel ";
    
    /**
     * Creates new form Tablero
     */
    public TableroVista() {
        initComponents();
        setTooltipNiveles();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        paTablero = new javax.swing.JPanel();
        paDetallle = new javax.swing.JPanel();
        laEntidad = new javax.swing.JLabel();
        laHabs = new javax.swing.JLabel();
        laHab1 = new javax.swing.JLabel();
        laHab2 = new javax.swing.JLabel();
        laHab3 = new javax.swing.JLabel();
        laHP = new javax.swing.JLabel();
        laDef = new javax.swing.JLabel();
        laAtt = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Zombi Defense");
        setName("frMain"); // NOI18N
        setResizable(false);
        setSize(new java.awt.Dimension(800, 600));
        getContentPane().setLayout(new java.awt.GridBagLayout());

        paTablero.setMinimumSize(new java.awt.Dimension(800, 400));
        paTablero.setPreferredSize(new java.awt.Dimension(800, 400));

        javax.swing.GroupLayout paTableroLayout = new javax.swing.GroupLayout(paTablero);
        paTablero.setLayout(paTableroLayout);
        paTableroLayout.setHorizontalGroup(
            paTableroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 800, Short.MAX_VALUE)
        );
        paTableroLayout.setVerticalGroup(
            paTableroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        getContentPane().add(paTablero, gridBagConstraints);

        paDetallle.setBackground(new java.awt.Color(153, 153, 153));
        paDetallle.setMinimumSize(new java.awt.Dimension(800, 200));
        paDetallle.setPreferredSize(new java.awt.Dimension(800, 200));

        laEntidad.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        laEntidad.setText("NombreEntidad");

        laHabs.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        laHabs.setText("Habilidad(es)");

        laHab1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        laHab1.setText("Habilidad1");

        laHab2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        laHab2.setText("Habilidad1");

        laHab3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        laHab3.setText("Habilidad1");

        laHP.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        laHP.setText("HP: 100");

        laDef.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        laDef.setText("Defensa: 10");

        laAtt.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        laAtt.setText("Ataque: 20");

        javax.swing.GroupLayout paDetallleLayout = new javax.swing.GroupLayout(paDetallle);
        paDetallle.setLayout(paDetallleLayout);
        paDetallleLayout.setHorizontalGroup(
            paDetallleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, paDetallleLayout.createSequentialGroup()
                .addGroup(paDetallleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(paDetallleLayout.createSequentialGroup()
                        .addGap(80, 80, 80)
                        .addGroup(paDetallleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(laHP)
                            .addComponent(laDef)
                            .addComponent(laAtt)))
                    .addGroup(paDetallleLayout.createSequentialGroup()
                        .addGap(62, 62, 62)
                        .addComponent(laEntidad)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 389, Short.MAX_VALUE)
                .addGroup(paDetallleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(laHabs)
                    .addComponent(laHab1)
                    .addComponent(laHab2)
                    .addComponent(laHab3))
                .addGap(141, 141, 141))
        );
        paDetallleLayout.setVerticalGroup(
            paDetallleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paDetallleLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(paDetallleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(laEntidad)
                    .addComponent(laHabs))
                .addGap(18, 18, 18)
                .addGroup(paDetallleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(laHab1)
                    .addComponent(laHP))
                .addGap(18, 18, 18)
                .addGroup(paDetallleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(laHab2)
                    .addComponent(laDef))
                .addGap(18, 18, 18)
                .addGroup(paDetallleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(laHab3)
                    .addComponent(laAtt))
                .addGap(0, 58, Short.MAX_VALUE))
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridheight = java.awt.GridBagConstraints.RELATIVE;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.SOUTHWEST;
        getContentPane().add(paDetallle, gridBagConstraints);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel laAtt;
    private javax.swing.JLabel laDef;
    private javax.swing.JLabel laEntidad;
    private javax.swing.JLabel laHP;
    private javax.swing.JLabel laHab1;
    private javax.swing.JLabel laHab2;
    private javax.swing.JLabel laHab3;
    private javax.swing.JLabel laHabs;
    private javax.swing.JPanel paDetallle;
    private javax.swing.JPanel paTablero;
    // End of variables declaration//GEN-END:variables

    public void setTooltipNiveles() {
        laHab2.setToolTipText(tooltipNivelHab + Constantes.PJ_NivelHab2 + ".");
        laHab3.setToolTipText(tooltipNivelHab + Constantes.PJ_NivelHab3 + ".");
    }
}
