package vista;

import control.Constantes;
import item.Objeto;
import java.awt.Component;
import java.util.ArrayList;
import javax.swing.DefaultListCellRenderer;
import javax.swing.JLabel;
import javax.swing.JList;
import javax.swing.JPanel;

/**
 *
 * @author moral
 */
public class TableroVista extends javax.swing.JFrame {
    
    private String tooltipNivelHab = "Se consigue en el nivel ";

    /**
     * Creates new form Tablero
     */
    public TableroVista() {
        initComponents();
        setTooltipNiveles();
        ocultarDetalles();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        paTablero = new javax.swing.JPanel();
        paDetallle = new javax.swing.JPanel();
        laEntidad = new javax.swing.JLabel();
        laHabs = new javax.swing.JLabel();
        laHab1 = new javax.swing.JLabel();
        laHab2 = new javax.swing.JLabel();
        laHab3 = new javax.swing.JLabel();
        laHP = new javax.swing.JLabel();
        laDef = new javax.swing.JLabel();
        laAtt = new javax.swing.JLabel();
        laEstado = new javax.swing.JLabel();
        botMover = new javax.swing.JButton();
        botAtacar = new javax.swing.JButton();
        botObj = new javax.swing.JButton();
        laInven = new javax.swing.JLabel();
        paInven = new javax.swing.JScrollPane();
        lisInven = new javax.swing.JList<>();
        lisInven.setCellRenderer(new DefaultListCellRenderer() {
            @Override
            public Component getListCellRendererComponent(JList<?> list, Object value, int index, boolean isSelected, boolean cellHasFocus) {
                Component renderer = super.getListCellRendererComponent(list, value, index, isSelected, cellHasFocus);
                if (renderer instanceof JLabel && value instanceof Objeto) {
                    ((JLabel) renderer).setText(((Objeto) value).nombre);
                }
                return renderer;
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Zombi Defense");
        setName("frMain"); // NOI18N
        setResizable(false);
        setSize(new java.awt.Dimension(800, 600));
        getContentPane().setLayout(new java.awt.GridBagLayout());

        paTablero.setMinimumSize(new java.awt.Dimension(800, 400));
        paTablero.setPreferredSize(new java.awt.Dimension(800, 400));
        paTablero.setLayout(new java.awt.GridLayout(10, 20));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        getContentPane().add(paTablero, gridBagConstraints);

        paDetallle.setBackground(new java.awt.Color(153, 153, 153));
        paDetallle.setMinimumSize(new java.awt.Dimension(800, 200));
        paDetallle.setPreferredSize(new java.awt.Dimension(800, 200));

        laEntidad.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        laEntidad.setText("NombreEntidad");

        laHabs.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        laHabs.setText("Habilidad(es)");

        laHab1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        laHab1.setText("Habilidad1");

        laHab2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        laHab2.setText("Habilidad1");

        laHab3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        laHab3.setText("Habilidad1");

        laHP.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        laHP.setText("HP: 100");

        laDef.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        laDef.setText("Defensa: 10");

        laAtt.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        laAtt.setText("Ataque: 20");

        laEstado.setFont(new java.awt.Font("Tahoma", 2, 14)); // NOI18N
        laEstado.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        laEstado.setText("Turno del Jugador");

        botMover.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        botMover.setText("Mover");

        botAtacar.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        botAtacar.setText("Atacar");

        botObj.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        botObj.setText("Usar objeto");

        laInven.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        laInven.setText("Inventario");

        lisInven.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lisInven.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        paInven.setViewportView(lisInven);

        javax.swing.GroupLayout paDetallleLayout = new javax.swing.GroupLayout(paDetallle);
        paDetallle.setLayout(paDetallleLayout);
        paDetallleLayout.setHorizontalGroup(
            paDetallleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paDetallleLayout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(paDetallleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(paDetallleLayout.createSequentialGroup()
                        .addComponent(laEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 735, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(paDetallleLayout.createSequentialGroup()
                        .addGroup(paDetallleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(laHP)
                            .addComponent(laDef)
                            .addComponent(laAtt)
                            .addComponent(laEntidad))
                        .addGap(50, 50, 50)
                        .addGroup(paDetallleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(laHabs)
                            .addComponent(laHab1)
                            .addComponent(laHab2)
                            .addComponent(laHab3))
                        .addGap(50, 50, 50)
                        .addGroup(paDetallleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(paInven, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(paDetallleLayout.createSequentialGroup()
                                .addGap(81, 81, 81)
                                .addComponent(laInven)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 65, Short.MAX_VALUE)
                        .addGroup(paDetallleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(botAtacar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(botObj, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(botMover, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(68, 68, 68))))
        );

        paDetallleLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {botAtacar, botMover, botObj});

        paDetallleLayout.setVerticalGroup(
            paDetallleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paDetallleLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(paDetallleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(paDetallleLayout.createSequentialGroup()
                        .addComponent(botMover)
                        .addGap(20, 20, 20)
                        .addComponent(botAtacar)
                        .addGap(20, 20, 20)
                        .addComponent(botObj))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, paDetallleLayout.createSequentialGroup()
                        .addComponent(laEstado)
                        .addGap(27, 27, 27)
                        .addGroup(paDetallleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(laEntidad)
                            .addComponent(laHabs)
                            .addComponent(laInven))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(paDetallleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(paDetallleLayout.createSequentialGroup()
                                .addGroup(paDetallleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                                    .addComponent(laHP)
                                    .addComponent(laHab1))
                                .addGap(15, 15, 15)
                                .addGroup(paDetallleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                                    .addComponent(laDef)
                                    .addComponent(laHab2))
                                .addGap(15, 15, 15)
                                .addGroup(paDetallleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                                    .addComponent(laAtt)
                                    .addComponent(laHab3)))
                            .addComponent(paInven, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(0, 25, Short.MAX_VALUE))
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridheight = java.awt.GridBagConstraints.RELATIVE;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.SOUTHWEST;
        getContentPane().add(paDetallle, gridBagConstraints);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botAtacar;
    private javax.swing.JButton botMover;
    private javax.swing.JButton botObj;
    private javax.swing.JLabel laAtt;
    private javax.swing.JLabel laDef;
    private javax.swing.JLabel laEntidad;
    private javax.swing.JLabel laEstado;
    private javax.swing.JLabel laHP;
    private javax.swing.JLabel laHab1;
    private javax.swing.JLabel laHab2;
    private javax.swing.JLabel laHab3;
    private javax.swing.JLabel laHabs;
    private javax.swing.JLabel laInven;
    private javax.swing.JList<Objeto> lisInven;
    private javax.swing.JPanel paDetallle;
    private javax.swing.JScrollPane paInven;
    private javax.swing.JPanel paTablero;
    // End of variables declaration//GEN-END:variables

    public JPanel getPanelTablero() {
        return this.paTablero;
    }
    
    private void setTooltipNiveles() {
        laHab2.setToolTipText(tooltipNivelHab + Constantes.PJ_NivelHab2 + ".");
        laHab3.setToolTipText(tooltipNivelHab + Constantes.PJ_NivelHab3 + ".");
    }
    
    public void ocultarDetalles() {
        laEstado.setText("Selecciona algo para ver más detalles.");
        laEstado.setVisible(true);
        laEntidad.setVisible(false);
        laHP.setVisible(false);
        laDef.setVisible(false);
        laAtt.setVisible(false);
        laHabs.setVisible(false);
        laHab1.setVisible(false);
        laHab2.setVisible(false);
        laHab3.setVisible(false);
        laInven.setVisible(false);
        paInven.setVisible(false);
        botMover.setVisible(false);
        botAtacar.setVisible(false);
        botObj.setVisible(false);
    }
    
    public void actulizarStats(String nombre, String vida, String def, String att, String[] habilidades) {
        laEstado.setVisible(false);
        laEntidad.setText(nombre);
        laEntidad.setVisible(true);
        laHP.setText("HP: " + vida);
        laHP.setVisible(true);
        laDef.setText("Defensa: " + def);
        laDef.setVisible(true);
        laAtt.setText("Ataque: " + att);
        laAtt.setVisible(true);
        laHabs.setVisible(true);
        laHab1.setVisible(true);
        if (habilidades.length == 1) {
            laHab1.setText(habilidades[0]);
        } else {
            laHab1.setText(habilidades[0]);
            laHab2.setText(habilidades[1]);
            laHab2.setVisible(true);
            laHab3.setText(habilidades[2]);
            laHab3.setVisible(true);
        }
    }
    
    public void actualizarInven(ArrayList<Objeto> inv) {
        laInven.setVisible(true);
        paInven.setVisible(true);
        lisInven.setModel(new ArrayList_ListModel<>(inv));
    }
    
    public void setAccionMover(boolean estado) {
        botAtacar.setVisible(true);
        botAtacar.setEnabled(estado);
    }
    
    public void setAccionAtacar(boolean estado) {
        botMover.setVisible(true);
        botMover.setEnabled(estado);
    }
    
    public void setAccionUsarObj(boolean estado) {
        botObj.setVisible(true);
        botObj.setEnabled(estado);
    }    
}
